import { Product, Category, Order } from "./types"

export const WHATSAPP_NUMBER = "254710776500"

export const CATEGORIES: Category[] = [
  { key: "all", label: "All Products", emoji: "✨" },
  { key: "sweaters", label: "Sweaters", emoji: "🧶" },
  { key: "blankets", label: "Blankets", emoji: "🌸" },
  { key: "totes", label: "Tote Bags", emoji: "👜" },
  { key: "scrunchies", label: "Scrunchies", emoji: "💫" },
]

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Scarlet Chunky Sweater",
    category: "sweaters",
    price: 3200,
    badge: "Bestseller",
    emoji: "🧶",
    desc: "Thick, warm, and irresistibly cozy. Hand-crocheted in a rich scarlet red with a relaxed fit perfect for cold evenings. Made with premium acrylic-wool blend yarn.",
    colors: ["#C41E3A", "#F5E6E8", "#8B2635"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 12,
  },
  {
    id: 2,
    name: "Ivory Oversized Cardigan",
    category: "sweaters",
    price: 3800,
    badge: "New",
    emoji: "🧣",
    desc: "Flowy, open-front cardigan crocheted in soft ivory yarn. A timeless layering piece for any season. Pairs beautifully over dresses or jeans.",
    colors: ["#FAF0E6", "#C41E3A", "#D4A574"],
    sizes: ["S", "M", "L", "XL"],
    stock: 8,
  },
  {
    id: 3,
    name: "Rosebud Baby Blanket",
    category: "blankets",
    price: 2400,
    badge: "Gift Pick",
    emoji: "🌸",
    desc: "Delicate rosebud-stitch blanket crocheted in blush and cream. The perfect welcome gift for a new little one. Soft, washable, and utterly precious.",
    colors: ["#F5E6E8", "#FAFAFA", "#E8C4C4"],
    sizes: ["One Size"],
    stock: 15,
  },
  {
    id: 4,
    name: "Red Wave Throw Blanket",
    category: "blankets",
    price: 4500,
    badge: "Popular",
    emoji: "🌊",
    desc: "Bold wave-stitch throw in deep crimson and white. Makes any couch look like a magazine cover. Large enough to wrap yourself in completely.",
    colors: ["#C41E3A", "#FFFFFF", "#8B2635"],
    sizes: ["One Size"],
    stock: 6,
  },
  {
    id: 5,
    name: "Market Tote Bag",
    category: "totes",
    price: 1800,
    badge: "Eco Pick",
    emoji: "👜",
    desc: "Spacious, durable market tote in natural cotton yarn with a pop of red trim. Handles groceries, books, beach days, and everything in between.",
    colors: ["#F5E6E8", "#C41E3A", "#D4A574"],
    sizes: ["One Size"],
    stock: 20,
  },
  {
    id: 6,
    name: "Mini Crochet Tote",
    category: "totes",
    price: 1400,
    badge: "Cute",
    emoji: "🛍️",
    desc: "Adorable mini tote just the right size for your essentials. A statement accessory that levels up any outfit instantly.",
    colors: ["#C41E3A", "#FFFFFF", "#F5E6E8"],
    sizes: ["One Size"],
    stock: 18,
  },
  {
    id: 7,
    name: "Scarlet Scrunchie Set (×3)",
    category: "scrunchies",
    price: 650,
    badge: "Bundle",
    emoji: "💫",
    desc: "Set of three hand-crocheted scrunchies in complementary red tones. Gentle on your hair and gorgeous in photos.",
    colors: ["#C41E3A", "#E8737C", "#F5A5AB"],
    sizes: ["One Size"],
    stock: 35,
  },
  {
    id: 8,
    name: "Pearl & Red Scrunchie",
    category: "scrunchies",
    price: 380,
    badge: "New",
    emoji: "🤍",
    desc: "A classic pearl-white scrunchie with a subtle red detail. Elegant enough for a night out, easy enough for everyday wear.",
    colors: ["#FAFAFA", "#C41E3A"],
    sizes: ["One Size"],
    stock: 42,
  },
  {
    id: 9,
    name: "Red Crop Sweater",
    category: "sweaters",
    price: 2800,
    emoji: "🌹",
    desc: "Chic cropped sweater in bold red. Perfect for pairing with high-waisted bottoms for a trendy, put-together look.",
    colors: ["#C41E3A", "#8B2635"],
    sizes: ["XS", "S", "M", "L"],
    stock: 10,
  },
  {
    id: 10,
    name: "Heirloom Lap Blanket",
    category: "blankets",
    price: 3200,
    badge: "Handpicked",
    emoji: "🏡",
    desc: "A gorgeous lap blanket with traditional granny-square motifs in red and white. The kind of piece you pass down.",
    colors: ["#C41E3A", "#FAFAFA", "#F5E6E8"],
    sizes: ["One Size"],
    stock: 9,
  },
]

// ── Mock Analytics Data ────────────────────────────────────────────────────────

export const MONTHLY_REVENUE = [
  { month: "Aug", revenue: 28400, orders: 34 },
  { month: "Sep", revenue: 35200, orders: 42 },
  { month: "Oct", revenue: 42100, orders: 51 },
  { month: "Nov", revenue: 58600, orders: 70 },
  { month: "Dec", revenue: 74300, orders: 89 },
  { month: "Jan", revenue: 45800, orders: 55 },
  { month: "Feb", revenue: 52100, orders: 63 },
  { month: "Mar", revenue: 61400, orders: 74 },
]

export const CATEGORY_SALES = [
  { name: "Sweaters", value: 38, color: "#C41E3A" },
  { name: "Blankets", value: 28, color: "#8B2635" },
  { name: "Tote Bags", value: 22, color: "#E8737C" },
  { name: "Scrunchies", value: 12, color: "#F5A5AB" },
]

export const TOP_PRODUCTS = [
  { name: "Scarlet Chunky Sweater", sales: 89, revenue: 284800 },
  { name: "Red Wave Throw Blanket", sales: 54, revenue: 243000 },
  { name: "Ivory Oversized Cardigan", sales: 47, revenue: 178600 },
  { name: "Market Tote Bag", sales: 112, revenue: 201600 },
  { name: "Scarlet Scrunchie Set", sales: 198, revenue: 128700 },
]

// export const RECENT_ORDERS: Order[] = [
//   {
//     id: "LW-0089",
//     customer_name: "Amina Wanjiru",
//     customer_email: "amina@email.com",
//     customer_phone: "+254 712 345 678",
//     order_items: [],
//     total: 3200,
//     status: "delivered",
//     payment_method: "mpesa",
//     order_date: "2025-03-09",
//     delivery_address: "Westlands, Nairobi",
//     delivery_city: "Nairobi",
//     payment_status:"paid"
//   },
//   {
//     id: "LW-0088",
//     customer_name: "Zara Kimani",
//     customer_email: "zara@email.com",
//     customer_phone: "+254 722 987 654",
//     order_items: [],
//     total: 6300,
//     status: "shipped",
//     payment_method: "bank",
//     order_date: "2025-03-08",
//     delivery_address: "Karen, Nairobi",
//     delivery_city: "Nairobi",
//     payment_status:"refunded"
//   },
//   {
//     id: "LW-0087",
//     customer_name: "Lydia Ochieng",
//     customer_email: "lydia@email.com",
//     customer_phone: "+254 733 111 222",
//     order_items: [],
//     total: 1800,
//     status: "processing",
//     payment_method: "mpesa",
//     order_date: "2025-03-08",
//     delivery_address: "Kilimani, Nairobi",
//     delivery_city: "Nairobi",
//     payment_status:"unpaid"
//   },
//   {
//     id: "LW-0086",
//     customer_name: "Faith Muthoni",
//     customer_email: "faith@email.com",
//     customer_phone: "+254 700 444 555",
//     order_items: [],
//     total: 4500,
//     status: "pending",
//     payment_method: "cash",
//     order_date: "2025-03-07",
//     delivery_address: "Lavington, Nairobi",
//     delivery_city: "Nairobi",
//     payment_status:"paid"
//   },
//   {
//     id: "LW-0085",
//     customer_name: "Grace Akinyi",
//     customer_email: "grace@email.com",
//     customer_phone: "+254 711 777 888",
//     order_items: [],
//     total: 760,
//     status: "delivered",
//     payment_method: "mpesa",
//     order_date: "2025-03-06",
//     delivery_address: "Eastlands",
//     delivery_city: "Nairobi",
//     payment_status:"failed"
//   },
//   {
//     id: "LW-0084",
//     customer_name: "Naomi Chebet",
//     customer_email: "naomi@email.com",
//     customer_phone: "+254 799 333 111",
//     order_items: [],
//     total: 9800,
//     status: "delivered",
//     payment_method: "bank",
//     order_date: "2025-03-05",
//     delivery_address: "Runda, Nairobi",
//     delivery_city: "Nairobi",
//     payment_status:"unpaid"
//   },
// ]
